### ISSUE TITLE
integrate XS into SES-shim ci build / test

### ISSUE THREAD

**Issue by dckc** [endojs/endo#508] opened 2020-10-27 22:53 UTC
briefly...

https://github.com/Agoric/agoric-sdk/pull/1649 https://github.com/Agoric/agoric-sdk/blob/master/packages/xs-vat-worker/Makefile and see the submodule in https://github.com/Agoric/agoric-sdk/tree/master/packages/xs-vat-worker 

@kriskowal had a less than enthusiastic reply to the submodule approach

there's also the issue of doing this on macos, possibly using docker...

cc @warner @erights

**Comment by dckc** [comment] 2021-01-25 17:18
The xsnap package opens up other approaches to this.

ref https://github.com/Agoric/agoric-sdk/pull/2194 , https://github.com/Agoric/agoric-sdk/pull/2225

**Comment by dckc** [comment] 2021-04-05 17:39
I got a pass over the SES test suite running...

83 tests passed
16 tests failed

48 test scripts SKIPped for various reasons

details:
https://gist.github.com/dckc/75663ff47b714f4dbf10ecf6dd1f602c

**Comment by dckc** [comment] 2021-04-10 03:05
current status: 82bc8ebc

91 tests passed
58 tests failed

22 scripts skipped:
  - 7: babel
  - 1: `import.meta.url`
  - 14: boring `errors/` dir

details: https://gist.github.com/dckc/83bdc1a4febf4f5eed4b7f9f08097f61

**Comment by dckc** [comment] 2021-04-10 20:31
##  115 tests pass; 0 fail; 40 scripts SKIPped as of c61a2e9

I'm starting to feel pretty good about SES tests on XS. SKIPs are due to:

 - 1: `test-global-object-mutability.js` SIGSEGV https://github.com/Moddable-OpenSource/moddable/issues/627
 - 1: `test/test-break-function-eval.js` Function constructor bug https://github.com/Moddable-OpenSource/moddable/issues/623
 - 1: `test/error/test-assert-log.js` Symbol toString https://github.com/Moddable-OpenSource/moddable/issues/621
 - 4: v8 tests: `e.stack` is undefined; no `captureStackTrace` on XS
 - 1: `test/test-package.js` import.meta.url requires enabling the parser plugin: 'importMeta'",
 - 5: ava-xs console isn't like ava console
 - 3: `SES_IMPORT_REJECTED`
 - 2: `SES_HTML_COMMENT_REJECTED`
 - 22: `SES_EVAL_REJECTED` and only the lockdown layer is running in XS; no babel

In some cases, several tests in a script *should* work on XS but the mechanism for excluding is at the whole script level.

details: https://gist.github.com/dckc/ecdcc72e0537ad069033b4f37ba1e90b
https://github.com/endojs/endo/tree/535-ava-xs

**Comment by rowgraus** [comment] 2021-05-07 15:19
@dckc to check with @erights on the timeline for this.  Is it required prior to the Stress Test phase in 3 weeks?

**Comment by kriskowal** [comment] 2024-01-10 05:22
I’m closing this as a duplicate of #812 to be addressed by https://github.com/endojs/endo/pull/1847

**Comment by kriskowal** [comment] 2024-01-10 05:23
Reöpening because #1847 doesn’t address XS installation in CI. Tracking that here.

**Comment by kriskowal** [comment] 2024-09-25 19:39
Endo has CI for SES that verifies that Lockdown runs to completion on XS https://github.com/endojs/endo/pull/2465 and more to come in https://github.com/endojs/endo/issues/2259 persuant to https://github.com/endojs/endo/issues/400

**Closed by kriskowal** 2024-09-25 19:39 UTC
Labels: xsnap, kriskowal-review-2024-01, kriskowal-just-do-it-2024-01
