### ISSUE TITLE
Failed to install on Windows

### ISSUE THREAD

**Issue by Jack-Works** [endojs/endo#786] opened 2021-06-18 16:05 UTC
```
error C:\Users\Jack\Workspace\endo\node_modules\@endo\endo: Command failed.
Exit code: 1
Command: node src/postinstall.js
Arguments:
Directory: C:\Users\Jack\Workspace\endo\node_modules\@endo\endo
Output:
node:fs:582
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/C:/Users/Jack/Workspace/endo/packages/endo/mitm/node'
```

This script `@endo/endo/src/postinstall.js` is *nix only.

**Comment by mhofman** [comment] 2021-06-18 18:09
Any chance you could give WSL a try? WSL2 preferably. The pain to make things run under win32 nowadays is usually not worth it since WSL provides a fully functioning *nix environment.

**Comment by kriskowal** [comment] 2021-12-13 22:42
This should be fixed now with https://github.com/endojs/endo/pull/948 and I will attempt to reproduce.

**Comment by kriskowal** [comment] 2021-12-14 00:25
It seems that the problem of installing is solved, but there remain problems with running.

**Comment by kriskowal** [comment] 2022-01-27 18:22
I believe this issue is resolved. Please reopen if you have or anyone else has difficulty getting yarn, yarn install, yarn build, yarn test working end to end on Windows.

**Closed by kriskowal** 2022-01-27 18:22 UTC
