### ISSUE TITLE
React Native Incompatibility: "failed to delete intrinsics.[object Object]syncGenerator%6length"

### ISSUE THREAD

**Issue by EtDu** [endojs/endo#660] opened 2021-04-09 02:40 UTC
When running `lockdown.umd.js` inside Safari and calling `lockdown()`, the following error appears:
```
[Log] Removing intrinsics.%AsyncGenerator%.length
[Error] failed to delete intrinsics.[object Object]syncGenerator%6length
	Console Evaluation (Console Evaluation 1:2063)
	Console Evaluation (Console Evaluation 1:1937)
	Console Evaluation (Console Evaluation 1:2046)
	Console Evaluation (Console Evaluation 1:2074)
	Console Evaluation (Console Evaluation 1:5249)
	Console Evaluation (Console Evaluation 1:5306)
	Console Evaluation (Console Evaluation 2:3)
	evaluateWithScopeExtension
	(anonymous function)
	_wrapCall
< TypeError: Unable to delete property.
```

**Comment by kriskowal** [comment] 2021-05-07 15:51
@erights It looks like there’s a non-standard non-configurable `length` property on `AsyncGenerator`. On the one hand, this seems to be a Safari bug, and on the other this is probably safe to allow. Should we retitle this to “Add AsyncGenerator.length to allow-list to accommodate Safari” and do the work?

**Comment by erights** [comment] 2021-05-07 18:12
I know I've run SES on Safari before. Is this new? Also, `AsyncGenerator` is a function. Functions have a `length` property. I'll investigate. Don't do anything until we understand this.

What version of Safari?

**Comment by erights** [comment] 2021-05-07 22:55
To try diagnosing this, I visited https://ses-demo.netlify.app/demos/console/ using Safari Version 14.1 (16611.1.21.161.3) . I found that my old Safari bug came back! I reopened it at

https://bugs.webkit.org/show_bug.cgi?id=222538#c17

After I revise endo to workaround that bug, I'll get back to this one.

**Comment by erights** [comment] 2021-05-07 23:29
That one is in progress at https://github.com/endojs/endo/pull/711

**Comment by erights** [comment] 2021-05-07 23:34
I cannot reproduce this. While running on my development version of #711 , running a local http server, and visiting http://localhost:8080/demos/console/ I get no errors in the console when I refresh. That demo calls `lockdown` with no arguments, letting everything default. What `lockdown` arguments are you using?

**Comment by erights** [comment] 2021-05-07 23:43
Revising to
```js
lockdown({
  errorTaming: 'unsafe',
  stackFiltering: 'verbose',
  overrideTaming: 'severe',
});
```
I was still not able to reproduce. This sets all possibly relevant lockdown options to their non-default setting.

**Comment by erights** [comment] 2021-05-07 23:44
@EtDu @kumavis  What version of Safari are you using?

**Comment by kumavis** [comment] 2021-05-10 03:03
sorry for the safari/react-native confusion

**Comment by erights** [comment] 2022-08-02 06:40
@kumavis @EtDu what is the state of this? If it can now be closed, please close it.

**Comment by leotm** [comment] 2023-03-09 18:10
apologies for the necropost, appreciate the raising of this issue ^ and prev comments

i'm also looking into this here
- https://github.com/LavaMoat/docs/issues/16

> Revising to
> 
> ```js
> lockdown({
>   errorTaming: 'unsafe',
>   stackFiltering: 'verbose',
>   overrideTaming: 'severe',
> });
> ```
> 
> I was still not able to reproduce. This sets all possibly relevant lockdown options to their non-default setting.

after the revision

```console
undefined is not an object (evaluating '(_console = console)._errorOriginal.apply')
undefined is not an object (evaluating (_console = console)._errorOriginal.apply')
```

any thoughts appreciated while i continue debugging

**Comment by erights** [comment] 2023-03-14 13:24
Ok, with that diagnosis, I agree we should

> retitle this to “Add AsyncGenerator.length to allow-list to accommodate Safari” and do the work?

as @kriskowal suggests at https://github.com/endojs/endo/issues/660#issuecomment-834560524

Thanks @leotm !

Any idea why they do this?

**Comment by leotm** [comment] 2023-03-14 18:14
no problemo! makes sense ^ not figured the why yet, but cloned the repo and run the big [download](https://github.com/react-native-community/jsc-android-buildscripts/blob/32c2dbbab0b0e8e945e1c61caa281be5308de947/package.json#L25) (1.12GB) script to see (there's also various [patches](https://github.com/react-native-community/jsc-android-buildscripts/tree/main/patches) going on and issues, but none related to the `length`)

**Closed** 2023-03-15 18:42 UTC
Labels: lavamoat
